#!/bin/sh
NEAT="/path/to/neatlibc"
CC="/path/to/neatcc/ncc"
LD="/path/to/neatld/nld"

CPPFLAGS="-Dfloat=long -Ddouble=long -D__extension__="

for x in $*
do
	if [ "$x" == "-c" ]
	then
		exec ${CC} ${CPPFLAGS} -I${NEAT} $*
	fi
done

exec ${LD} $* ${NEAT}/start.o ${NEAT}/libc.a
